-- SQLite NOCASE only folds ASCII. These versioned keys are generated by the
-- Host's deterministic project_path_key() function so Windows Unicode path
-- identity never depends on a SQLite collation.
ALTER TABLE project_source_roots ADD COLUMN path_key TEXT;
ALTER TABLE workspace_locations ADD COLUMN path_key TEXT;
ALTER TABLE import_candidates ADD COLUMN root_path_key TEXT;

UPDATE project_source_roots
SET path_key = project_path_key(normalized_path);

UPDATE workspace_locations
SET path_key = project_path_key(normalized_path);

UPDATE import_candidates
SET root_path_key = project_path_key(root_normalized_path);

-- Creating these indexes intentionally fails when a v4 database already has
-- Unicode case-equivalent rows. migrateDatabase retains its pre-v5 backup and
-- rolls the whole migration back instead of choosing or deleting a record.
CREATE UNIQUE INDEX project_source_roots_path_key_unique
  ON project_source_roots(path_key);

CREATE UNIQUE INDEX workspace_locations_active_path_key_unique
  ON workspace_locations(path_key)
  WHERE is_active = 1;

CREATE UNIQUE INDEX import_candidates_job_path_key_unique
  ON import_candidates(import_job_id, root_path_key);

CREATE INDEX import_candidates_root_path_key_idx
  ON import_candidates(root_path_key, candidate_id);

DROP INDEX project_source_roots_normalized_path_nocase_unique;
DROP INDEX workspace_locations_active_path_nocase_unique;

-- SQLite cannot add a NOT NULL/check constraint to an existing column without
-- rebuilding these tables. Guards provide the same invariant with a smaller,
-- safer migration and also reject direct writes that omit or forge a path key.
CREATE TRIGGER project_source_roots_path_key_insert_guard
BEFORE INSERT ON project_source_roots
WHEN NEW.path_key IS NULL
  OR NEW.path_key <> project_path_key(NEW.normalized_path)
BEGIN
  SELECT RAISE(ABORT, 'project_source_roots.path_key mismatch');
END;

CREATE TRIGGER project_source_roots_path_key_update_guard
BEFORE UPDATE OF normalized_path, path_key ON project_source_roots
WHEN NEW.path_key IS NULL
  OR NEW.path_key <> project_path_key(NEW.normalized_path)
BEGIN
  SELECT RAISE(ABORT, 'project_source_roots.path_key mismatch');
END;

CREATE TRIGGER workspace_locations_path_key_insert_guard
BEFORE INSERT ON workspace_locations
WHEN NEW.path_key IS NULL
  OR NEW.path_key <> project_path_key(NEW.normalized_path)
BEGIN
  SELECT RAISE(ABORT, 'workspace_locations.path_key mismatch');
END;

CREATE TRIGGER workspace_locations_path_key_update_guard
BEFORE UPDATE OF normalized_path, path_key ON workspace_locations
WHEN NEW.path_key IS NULL
  OR NEW.path_key <> project_path_key(NEW.normalized_path)
BEGIN
  SELECT RAISE(ABORT, 'workspace_locations.path_key mismatch');
END;

CREATE TRIGGER import_candidates_path_key_insert_guard
BEFORE INSERT ON import_candidates
WHEN NEW.root_path_key IS NULL
  OR NEW.root_path_key <> project_path_key(NEW.root_normalized_path)
BEGIN
  SELECT RAISE(ABORT, 'import_candidates.root_path_key mismatch');
END;

CREATE TRIGGER import_candidates_path_key_update_guard
BEFORE UPDATE OF root_normalized_path, root_path_key ON import_candidates
WHEN NEW.root_path_key IS NULL
  OR NEW.root_path_key <> project_path_key(NEW.root_normalized_path)
BEGIN
  SELECT RAISE(ABORT, 'import_candidates.root_path_key mismatch');
END;
